/*
Proverbs 20:18:
   Bread obtained by falsehood is sweet to a man, But afterward his mouth will be filled with gravel.

We worked really hard for this project. Although we dont care if you enhance it and publish, we would care
if you copy it and claim our work as your own. Although it might feel good, to take the credit, you would ultimatly
regret it. But please feel free to change the files and publish putting your name up as well as ours.
We will also not get into legalities. but please dont take advantage that we dont use
legalities. Instead, treat us with respect like we treat you. 

Sincerely
The AJS Dev Team.

*/
this.lang = [];
this.lang[0] = { original:["[Bot] ",": Wandering"],replaceto:[ "[Bot]", ": errante"]};
this.lang[1] = { original:["[Bot] ",": Getting Food"],replaceto:[ "[Bot]", ": Obtención de Alimentos"]};
this.lang[2] = { original:["[Bot] ",": Fleeing from ","[Bot] ",": Targeting ","[Bot] ",": Targeting (virus) ","team timeout"],replaceto:[ "[Bot]", ": Huyendo de", "[Bot]", ": Orientación", "[Bot]", ": Targeting (virus)", "equipo de tiempo de espera"]};
this.lang[3] = { original:["[Bot] ",": Fleeing from ","ok true","ejecting"],replaceto:[ "[Bot]", ": Huyendo de", "ok verdadero", "expulsión"]};
this.lang[4] = { original:["[\x1b[32mOK\x1b[0m] Uniban updated"],replaceto:[ "[\x1b[32mOK\x1b[0m] Uniban actualiza"]};
this.lang[5] = { original:["[\x1b[34mINFO\x1b[0m] No config files found, generating: src/settings/config.ini"],replaceto:[ "[\x1b[34mINFO\x1b[0m] No se encontraron archivos de configuración, generando: src / settings / config.ini"]};
this.lang[6] = { original:["[\x1b[34mINFO\x1b[0m] Override not found... Generating new override"],replaceto:[ "[\x1b[34mINFO\x1b[0m] Invalidar que no se encuentra ... Generación de nuevos anular"]};
this.lang[7] = { original:["[\x1b[34mINFO\x1b[0m] Banned.txt not found... Generating new banned.txt"],replaceto:[ "[\x1b[34mINFO\x1b[0m] Banned.txt no encontrado ... Generación de nuevos banned.txt"]};
this.lang[8] = { original:["[\x1b[34mINFO\x1b[0m] opbyip.txt not found... Generating new opbyip.txt"],replaceto:[ "[\x1b[34mINFO\x1b[0m] opbyip.txt que no se encuentra ... Generación de nuevos opbyip.txt"]};
this.lang[9] = { original:["[\x1b[34mINFO\x1b[0m] highscores.txt not found... Generating new highscores.txt"],replaceto:[ "[\x1b[34mINFO\x1b[0m] highscores.txt not found ... Generación de nuevos highscores.txt"]};
this.lang[10] = { original:["[\x1b[34mINFO\x1b[0m] Generating customskin.txt..."],replaceto:[ "[\x1b[34mINFO\x1b[0m] La generación de customskin.txt ..."]};
this.lang[11] = { original:["[\x1b[31mFAIL\x1b[0m] Could not fetch data from servers... will generate empty file"],replaceto:[ "[\x1b[31mFAIL\x1b[0m] No se pudo obtener datos de los servidores ... va a generar archivo vacío"]};
this.lang[12] = { original:["\x1b[32m[Game] Ogar Unlimited - An open source Agar.io server implementation"],replaceto:[ "\x1b[32m[Juego] Ogro ilimitado - una implementación de código abierto del servidor Agar.io"]};
this.lang[13] = { original:["[Game] By The AJS development team\x1b[0m"],replaceto:[ "[Juego] Por AJS El equipo de desarrollo de \X1B[0m"]};
this.lang[14] = { original:["[Console] Invalid Command, try \u001B[33mhelp\u001B[0m for a list of commands."],replaceto:[ "[Consola] Comando no válido, intente \u001B[33mhelp\u001B[0m para obtener una lista de comandos."]};
this.lang[15] = { original:["[","] Loaded "," player bots"],replaceto:[ "[", "] Loaded", "robots de jugador"]};
this.lang[16] = { original:["[Error] Please make sure you are running Ogar with root privileges."],replaceto:[ "[Error] Por favor asegúrese de que está ejecutando Ogro con privilegios de root."]};
this.lang[17] = { original:["[","] Client ",", tried to connect but is banned!"],replaceto:[ "[", "] Cliente", "tratado de conectar, pero está prohibido!"]};
this.lang[18] = { original:["[","] A player with an IP of "," joined the game"],replaceto:[ "[", "] Un jugador con una IP de", "se unió al juego"]};
this.lang[19] = { original:["[","] A player with an IP of "," left the game"],replaceto:[ "[", "] Un jugador con una IP de", "dejó el juego"]};
this.lang[20] = { original:["[","] User tried to spawn with "," but was denied!"],replaceto:[ "[", "] El usuario ha intentado generar con" , "pero se negó!"]};
this.lang[21] = { original:["[","] The Game Was Paused to save memory. Join the game to resume!"],replaceto:[ "[", "] El juego se detuvo para ahorrar memoria. Entrar en el juego para reanudar!"]};
this.lang[22] = { original:["[Console] Command 36 recieved"],replaceto:[ "[Consola] Comando 36 recibió"]};
this.lang[23] = { original:["[Console] Command 51 recieved"],replaceto:[ "[Consola] Comando 51 recibió"]};
this.lang[24] = { original:["[Console] Command 51 recieved"],replaceto:[ "[Consola] Comando 51 recibió"]};
this.lang[25] = { original:["[Console] Initiating Autoupdate\x1b[0m"],replaceto:[ "[Consola] El inicio de Autoupdate \X1B[0m"]};
this.lang[26] = { original:["[Console] To update quickly, use the update command!\x1b[0m"],replaceto:[ "[Consola] para actualizar rápidamente, utilice el comando de actualización! \X1B[0m"]};
this.lang[27] = { original:["\x1b[32m[Console] We recieved a world-wide message!: ","\x1b[0m"],replaceto:[ "\x1b[32m[consola] Nos recibió un mensaje en todo el mundo !:", "\X1B[0m"]};
this.lang[28] = { original:["[Console] Could not connect to servers. Aborted checking for updates and messages"],replaceto:[ "[Consola] No se pudo conectar a los servidores. Abortada la comprobación de actualizaciones y mensajes"]};
this.lang[29] = { original:["[Console] Command 45 recieved"],replaceto:[ "[Consola] Comando 45 recibió"]};
this.lang[30] = { original:["[Console] Command 36 recieved"],replaceto:[ "[Consola] Comando 36 recibió"]};
this.lang[31] = { original:["[Console] Command 51 recieved"],replaceto:[ "[Consola] Comando 51 recibió"]};
this.lang[32] = { original:["[Console] Command 51 recieved"],replaceto:[ "[Consola] Comando 51 recibió"]};
this.lang[33] = { original:["[Console] Initiating Autoupdate\x1b[0m"],replaceto:[ "[Consola] El inicio de Autoupdate \X1B[0m"]};
this.lang[34] = { original:["[Console] To update quickly, use the update command!\x1b[0m"],replaceto:[ "[Consola] para actualizar rápidamente, utilice el comando de actualización! \X1B[0m"]};
this.lang[35] = { original:["[Update] Downloaded ","[Update] Downloaded ","Highscore:","  By  ","moving"],replaceto:[ "[Actualización] descargado", "[Actualización] descargado", "Record:", "Por", "movimiento"]};
this.lang[36] = { original:["[Console] Running garbage collect to reduce memory"],replaceto:[ "[Consola] Ejecución de recoger la basura para reducir la memoria"]};
this.lang[37] = { original:["[Console] Invalid Command, try \u001B[33mhelp\u001B[0m for a list of commands."],replaceto:[ "[Consola] Comando no válido, intente \u001B[33mhelp \u001B[0m para obtener una lista de comandos."]};
this.lang[38] = { original:["[Console] "," has issued a remote command "," and is logged in!"],replaceto:[ "[Consola]", "ha emitido un comando remoto", "y está conectado!"]};
this.lang[39] = { original:["[WARN] Stopped crash at packethandler. Probably because of wrong packet/client . Usually normal."],replaceto:[ "[WARN] Detenido accidente en packethandler. Probablemente a causa de mal de paquetes / cliente. Por lo general, normal."]};
this.lang[40] = { original:["[\x1b[34mINFO\x1b[0m] Loading plugins in dev mode"],replaceto:[ "[\x1b[34mINFO\x1b[0m] Carga de plugins en el modo dev"]};
this.lang[41] = { original:["[\x1b[32mOK\x1b[0m] loaded plugin: "," By "," version ","[\x1b[31mFAIL\x1b[0m]Didnt load pluginfile "," because it was missing parameters"],replaceto:[ "[\x1b[32mOK\x1b[0m] plugin de carga:", "Por", "versión", "[\x1b[31mFAIL\x1b[0m] Didnt pluginfile de carga", "porque faltaba parámetros"]};
this.lang[42] = { original:["[\x1b[34mINFO\x1b[0m] Loading plugins"],replaceto:[ "[\x1b[34mINFO\x1b[0m] Carga de plugins"]};
this.lang[43] = { original:["[\x1b[31mFAIL\x1b[0m] Failed to load pluginfile "," Reason: ","[\x1b[31mFAIL\x1b[0m] Couldnt load plugins"],replaceto:[ "[\x1b[31mFAIL\x1b[0m] No se ha podido cargar pluginfile", "Motivo:", "[\x1b[31mFAIL\x1b[0m] No podía plugins de carga"]};
this.lang[44] = { original:["[Console] Updating..."],replaceto:[ "[Consola] Actualizando ..."]};
this.lang[45] = { original:["An op (",") Used the Q key"],replaceto:[ "Un artículo (", ") Se utiliza la tecla Q"]};
this.lang[46] = { original:["An op (",") Added 100 more mass"],replaceto:[ "Un artículo (", ") añadida 100 más masa"]};
this.lang[47] = { original:["An op (",") Shot a virus"],replaceto:[ "Un artículo (", ") tras un virus"]};
this.lang[48] = { original:["An op (",") Shot a troll virus"],replaceto:[ "Un artículo (", ") tras un virus duende"]};
this.lang[49] = { original:["An op (",") Shot Anti-Matter food"],replaceto:[ "Un artículo (", ") Disparo de alimentos Anti-Matter"]};
this.lang[50] = { original:["An op (",") Shot a Explode virus"],replaceto:[ "Un artículo (", ") tras estallar un virus"]};
this.lang[51] = { original:["Black Hole Spawned"],replaceto:[ "Agujero Negro Spawned"]};
this.lang[52] = { original:["Collided!"],replaceto:[ "Chocó!"]};
this.lang[53] = { original:["Test:"],replaceto:["Prueba:"]};
this.lang[54] = { original:["Proper Usage: node index.js"],replaceto:[ "El uso correcto: index.js nodo"]};
this.lang[55] = { original:["    --noconsole         Disables the console"],replaceto:[ "--noconsole Desactiva la consola"]};
this.lang[56] = { original:["    --help              Help menu."],replaceto:[ "Menú de Ayuda --help."]};
this.lang[57] = { original:["[Console] ======================= OP HELP ====================="],replaceto:[ "[Consola] ======================= OP AYUDA ==================== = "]};
this.lang[58] = { original:["You use OP by first setting who has op by doing op [id] in console. Then, that player can use the op features in game by pressing q. Then a c will appear next to your name. If you press w in this state, it gives you 100 more mass. If you press space in this state, you will be able to rejoin instantly. You will find out that if you press q again, two c's will appear next to your name. if you press w in this state, you shoot viruses. If you press space in this state, you shoot tiny things (almost invisible) that if someone eats, their mass is reduced by 100. Then, if you press q again,3 c's will appear.press w with 3c's, you shoot a virus, but whoever who eats it will be trolled :). If you press space with 3 c's the person who eats the virus will explode.If you press q again, 4 cs will appear and if you press w, you will shoot a virus tha kills people and space, it shoots a kick virus. You can then exit op by pressing q again after doing an action or by pressing Q until the three c's will dissappear (so that you can normally split and shoot mass)."],replaceto:[ "Se utiliza OP por primera configuración que tiene op haciendo op [id] en la consola. Luego, ese jugador puede utilizar las funciones operacionales en juego pulsando q. Entonces ac aparecerá junto a su nombre. Si pulsa w en este estado, se le da el 100 más masa. Si pulsa el espacio en este estado, usted será capaz de unirse al instante. va a descubrir que si presiona q otra vez, dos c del aparecerán junto a su nombre. Si presiona w en este estado, disparar virus. Si pulsa el espacio en este estado, se dispara cosas pequeñas (casi invisible) que si alguien come, su masa se reduce en 100. Entonces, si se pulsa de nuevo q, 3 c de Will appear.press w con 3C, se dispara un virus, pero el que quien lo come será controlada :). Si pulsa el espacio con 3 c de la persona que come el virus se explode.If presiona q de nuevo, aparecerá 4 cs y si presiona w , que va a capturar un tha virus mata gente y el espacio, que dispara un virus patada. a continuación, puede salir op pulsando q de nuevo después de hacer una acción o pulsando q hasta que las tres C se dissappear (de modo que normalmente se pueden dividir y disparar masa)."]};
this.lang[59] = { original:["[Console] ===================== OP Usage Map ==================="],replaceto:[ "[Consola] ===================== OP Uso Mapa ==================="]};
this.lang[60] = { original:["One C:"],replaceto:[ "Un C:"]};
this.lang[61] = { original:["W = Addmass 100+"],replaceto:[ "W = 100 + Addmass"]};
this.lang[62] = { original:["Space = Merge Instantly"],replaceto:[ "Espacio = Combinar de forma instantánea"]};
this.lang[63] = { original:["Two C's:"],replaceto:[ "Dos de C:"]};
this.lang[64] = { original:["W = Shoot virus"],replaceto:[ "W = disparar virus"]};
this.lang[65] = { original:["Space = Shoot Mass that decreases 100 mass from consumer"],replaceto:[ "Espacio = Disparar misa que disminuye la masa de 100 consumidores"]};
this.lang[66] = { original:["Three C's:"],replaceto:[ "Tres C:"]};
this.lang[67] = { original:["W = Troll virus"],replaceto:[ "Virus W = Troll"]};
this.lang[68] = { original:["Space = Explode virus"],replaceto:[ "Espacio = estalla el virus"]};
this.lang[69] = { original:["Four C's:"],replaceto:[ "Cuatro C:"]};
this.lang[70] = { original:["W = Kill virus"],replaceto:[ "Virus W = Kill"]};
this.lang[71] = { original:["Space = Kick Virus"],replaceto:[ "Espacio = Virus del retroceso"]};
this.lang[72] = { original:["[Console] ===================================================="],replaceto:[ "[Consola] ============================================= ======= "]};
this.lang[73] = { original:["[Console] ======================== HELP ======================"],replaceto:[ "[Consola] ======================== AYUDA ==================== == "]};
this.lang[74] = { original:["[Console] ophelp     : Shows OP help"],replaceto:[ "[Consola] ophelp: Shows ayuda OP"]};
this.lang[75] = { original:["[Console] addbot     : add bot to the server"],replaceto:[ "[Consola] addbot: añadir bot al servidor"]};
this.lang[76] = { original:["[Console] kickbots   : kick a specified amount of bots"],replaceto:[ "[Consola] kickbots: patear una cantidad especificada de los robots"]};
this.lang[77] = { original:["[Console] board      : set scoreboard text"],replaceto:[ "[Consola] board: establecer texto marcador"]};
this.lang[78] = { original:["[Console] Restart    : Restart server or set time till restart"],replaceto:[ "[Consola] Restart: Reiniciar el servidor o el tiempo establecido hasta reiniciar"]};
this.lang[79] = { original:["[Console] Announce   : Starts the auto announce for high scores"],replaceto:[ "[Consola] Announce: Inicia el auto anunciar por altas puntuaciones"]};
this.lang[80] = { original:["[Console] boardreset : reset scoreboard text"],replaceto:[ "[Consola] boardreset: restablecer el texto marcador"]};
this.lang[81] = { original:["[Console] Spawn      : Spawn things"],replaceto:[ "[Consola] spawn: cosas Spawn"]};
this.lang[82] = { original:["[Console] change     : change specified settings"],replaceto:[ "[Consola] change: el cambio configuración especificada"]};
this.lang[83] = { original:["[Console] clear      : clear console output"],replaceto:[ "[Consola] clear: salida de la consola clara"]};
this.lang[84] = { original:["[Console] color      : set cell(s) color by client ID"],replaceto:[ "[Consola] Color: Célula conjunto (s) de color por ID de cliente"]};
this.lang[85] = { original:["[Console] exit       : stop the server"],replaceto:[ "[Consola] exit: detener el servidor"]};
this.lang[86] = { original:["[Console] garbage    : Garbage collection"],replaceto:[ "[Consola] garbage: La recolección de basura"]};
this.lang[87] = { original:["[Console] food       : spawn food at specified Location"],replaceto:[ "[Consola] food: alimentos desove en la localización especificada"]};
this.lang[88] = { original:["[Console] Freeze     : Freezes a player"],replaceto:[ "[Consola] freeze: Congela un jugador"]};
this.lang[89] = { original:["[Console] spawnmass  : sets players spawn mass"],replaceto:[ "[Consola] spawnmass: fija los jugadores desovan en masa"]};
this.lang[90] = { original:["[Console] plugin     : Manage plugins "],replaceto:[ "[Consola] plugin: Administrar complementos"]};
this.lang[91] = { original:["[Console] Multiverse : Manage servers"],replaceto:[ "[Consola] Multiverse: Administrar servidores"]};
this.lang[92] = { original:["[Console] Chatban    : ban/unban people from chatting"],replaceto:[ "[Consola] chatban: prohibición / Desbloquear el acceso a las personas en el chat"]};
this.lang[93] = { original:["[Console] gamemode   : change server gamemode"],replaceto:[ "[Consola] gamemode: modo de juego servidor de cambio"]};
this.lang[94] = { original:["[Console] Quickrestart : Quickly restart the server in a rush. Not real restart"],replaceto:[ "[Consola] QuickRestart: reiniciar el servidor rápidamente en una carrera real de reinicio No"]};
this.lang[95] = { original:["[Console] kick       : kick player or bot by client ID"],replaceto:[ "[Consola] kick: reproductor de patada o bot por ID de cliente"]};
this.lang[96] = { original:["[Console] kill       : kill cell(s) by client ID"],replaceto:[ "[Consola] kill: matar a la célula (s) de identificación de cliente"]};
this.lang[97] = { original:["[Console] Reset      : Destroys everything and starts from scratch"],replaceto:[ "[Consola] Reset: Destruye todo y empieza de cero"]};
this.lang[98] = { original:["[Console] killall    : kill everyone"],replaceto:[ "[Consola] killall: matar a todos"]};
this.lang[99] = { original:["[Console] mass       : set cell(s) mass by client ID"],replaceto:[ "[Consola] Mass: Célula conjunto (s) de masas por ID de cliente"]};
this.lang[100] = { original:["[Console] Uniban     : lists unibanned people"],replaceto:[ "[Consola] Uniban: enumera unibanned la gente"]};
this.lang[101] = { original:["[Console] name       : change cell(s) name by client ID"],replaceto:[ "[Consola] Name: Célula cambio (s) nombre por ID de cliente"]};
this.lang[102] = { original:["[Console] playerlist : get list of players and bots"],replaceto:[ "[Consola] playerlist: obtener la lista de los jugadores y los robots"]};
this.lang[103] = { original:["[Console] pause      : pause game , freeze all cells"],replaceto:[ "[Consola] pause: la pausa del juego, congelar todas las células"]};
this.lang[104] = { original:["[Console] reload     : reload config"],replaceto:[ "[Consola] reload: recargar config"]};
this.lang[105] = { original:["[Console] Speed      : Sets a players base speed"],replaceto:[ "[Consola] speed: Establece una velocidad base de jugadores"]};
this.lang[106] = { original:["[Console] status     : get server status"],replaceto:[ "[Consola] status: obtener el estado del servidor"]};
this.lang[107] = { original:["[Console] tp         : teleport player to specified location"],replaceto:[ "[Consola] tp: reproductor de teletransporte a la ubicación especificada"]};
this.lang[108] = { original:["[Console] virus      : spawn virus at a specified Location"],replaceto:[ "[Consola] virus: el virus de la freza en una ubicación especificada"]};
this.lang[109] = { original:["[Console] Kickrange  : kicks in a ID range"],replaceto:[ "[Consola] Kickrange: patadas en un rango de ID"]};
this.lang[110] = { original:["[Console] Killrange  : kills in a ID range"],replaceto:[ "[Consola] Killrange: mata en un rango de ID"]};
this.lang[111] = { original:["[Console] Verify     : EasyVerify command"],replaceto:[ "[Consola] Verify: EasyVerify comando"]};
this.lang[112] = { original:["[Console] Hide       : Hides/unhides a player"],replaceto:[ "[Consola] Hide: Oculta / unhides un jugador"]};
this.lang[113] = { original:["[Console] Banrange   : Bans in a ID range"],replaceto:[ "[Consola] Banrange: Prohibiciones en un rango de ID"]};
this.lang[114] = { original:["[Console] Merge      : Forces that player to merge"],replaceto:[ "[Consola] Merge: Fuerzas ese jugador se fusionen"]};
this.lang[115] = { original:["[Console] Nojoin     : Prevents the player from merging"],replaceto:[ "[Consola] Nojoin: Evita que el jugador de la fusión"]};
this.lang[116] = { original:["[Console] Msg        : Sends a message"],replaceto:[ "[Consola] Msg: Envía un mensaje de"]};
this.lang[117] = { original:["[Console] Killbots   : Kills bots"],replaceto:[ "[Consola] Killbots: Mata a los robots"]};
this.lang[118] = { original:["[Console] Fmsg       : Sends a Force Message"],replaceto:[ "[Consola] FMSG: Envía un mensaje Force"]};
this.lang[119] = { original:["[Console] Pmsg       : Periodically sends a message"],replaceto:[ "[Consola] PMSG: Periódicamente envía un mensaje"]};
this.lang[120] = { original:["[Console] Spmsg      : Stops any Pmsg proccess"],replaceto:[ "[Consola] Spmsg: detiene cualquier proccess PMSG"]};
this.lang[121] = { original:["[Console] Pfmsg      : Periodically sends a force message"],replaceto:[ "[Consola] Pfmsg: Periódicamente envía un mensaje de fuerza"]};
this.lang[122] = { original:["[Console] Sfpmsg     : Stops any Pfmsg proccess"],replaceto:[ "[Consola] Sfpmsg: detiene cualquier proccess Pfmsg"]};
this.lang[123] = { original:["[Console] Rop        : Resets op"],replaceto:[ "[Consola] Rop: Restablece op"]};
this.lang[124] = { original:["[Console] Range      : does bulk command with players"],replaceto:[ "[Consola] Range: hace mando a granel con los jugadores"]};
this.lang[125] = { original:["[Console] Op         : Makes that player OP"],replaceto:[ "[Consola] Op: hace que ese jugador OP"]};
this.lang[126] = { original:["[Console] Dop        : De-Ops a player"],replaceto:[ "[Consola] Dop: De-ops un jugador"]};
this.lang[127] = { original:["[Console] Opbyip     : Allows ypu to control the opbyip feature"],replaceto:[ "[Consola] Opbyip: Permite ypu para controlar la función opbyip"]};
this.lang[128] = { original:["[Console] Ban        : Bans an IP and senda a msg saying that person was banned"],replaceto:[ "[Consola] Ban: Bans una IP y una senda msg diciendo que esa persona fue prohibida"]};
this.lang[129] = { original:["[Console] Banlist    : Lists banned IPs"],replaceto:[ "[Consola] banlist: Listas prohibidos IPs"]};
this.lang[130] = { original:["[Console] Clearban   : Resets Ban list"],replaceto:[ "[Consola] Clearban: Restablece Lista de no"]};
this.lang[131] = { original:["[Console] Resetvirus : Turns special viruses (from op's) into normal ones"],replaceto:[ "[Consola] Resetvirus: Activa virus especiales (de op) en las normales"]};
this.lang[132] = { original:["[Console] Split      : Splits a player"],replaceto:[ "[Consola] split: Divide un jugador"]};
this.lang[133] = { original:["[Console] Minion     : Creates minions that suicide into you"],replaceto:[ "[Consola] Minion: Crea secuaces que el suicidio en ti"]};
this.lang[134] = { original:["[Console] Team       : Changes a players Team"],replaceto:[ "[Consola] team: Cambia un equipo de jugadores"]};
this.lang[135] = { original:["[Console] Colortext  : changes text style"],replaceto:[ "[Consola] colorText: Cambios de estilo de texto"]};
this.lang[136] = { original:["[Console] Shrink     : Shrinks the game"],replaceto:[ "[Consola] Shrink: Reduce el juego"]};
this.lang[137] = { original:["[Console] Enlarge    : Enlargens the game"],replaceto:[ "[Consola] enlarge: Enlargens el juego"]};
this.lang[138] = { original:["[Console] Explode    : Explodes a player"],replaceto:[ "[Consola] explode: Explota un jugador"]};
this.lang[139] = { original:["[Console] Resetateam : Resets anti team effect for a player"],replaceto:[ "[Consola] Resetateam: Restablece efecto anti equipo para un jugador"]};
this.lang[140] = { original:["[Console] Rainbow    : Gives rainbow effect to a player"],replaceto:[ "[Consola] rainbow: Da efecto arco iris a un jugador"]};
this.lang[141] = { original:["[Console] Update     : Updates server to the latest version"],replaceto:[ "[Consola] Update: servidor de actualizaciones a la última versión"]};
this.lang[142] = { original:["[Console] Chat       : Chat using the console!"],replaceto:[ "[Consola] Chat: Chat mediante la consola"]};
this.lang[143] = { original:["[Console] changelog  : Shows a changelog"],replaceto:[ "[Consola] changelog: muestra una lista de cambios"]};
this.lang[144] = { original:["[Console] Added "," player bots"],replaceto:[ "[Consola] Añadido", "robots de jugador"]};
this.lang[145] = { original:["High Score announce system started"],replaceto:[ "High Score anunciar sistema comenzó"]};
this.lang[146] = { original:["[Console] Successfully set leaderboard"],replaceto:[ "[Consola] establecer con éxito la tabla de clasificación"]};
this.lang[147] = { original:["[Console] Successfully reset leaderboard"],replaceto:[ "[Consola] restablecer con éxito la tabla de posiciones"]};
this.lang[148] = { original:["[Console] Cleared recorded banlist"],replaceto:[ "[Consola] lista de ban registrado Borrado"]};
this.lang[149] = { original:["[Console] Successfully recorded banlist"],replaceto:[ "[Consola] lista de ban con éxito registrado"]};
this.lang[150] = { original:["[Console] Added "," to the banlist"],replaceto:[ "[Consola] Añadido", "a la lista de ban"]};
this.lang[151] = { original:["[Console] That IP is already banned"],replaceto:[ "[Consola] Eso IP ya está prohibido"]};
this.lang[152] = { original:["[Console] That IP is whitelisted"],replaceto:[ "[Consola] Eso IP está en la lista blanca"]};
this.lang[153] = { original:["[Console] Current banned IPs (",")"],replaceto:[ "[Consola] IPs prohibidas actuales (", ")"]};
this.lang[154] = { original:["[Console] Please specify a valid range!"],replaceto:[ "[Consola] Por favor, especifique un rango válido!"]};
this.lang[155] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[156] = { original:["[Console] Successfully changed leaderboard values"],replaceto:[ "[Consola] cambiado correctamente los valores de la tabla de clasificación"]};
this.lang[157] = { original:["[Console] Successfully reset leaderboard"],replaceto:[ "[Consola] restablecer con éxito la tabla de posiciones"]};
this.lang[158] = { original:["[Console] Please insert a valid value"],replaceto:[ "[Consola] Por favor, introduzca un valor válido"]};
this.lang[159] = { original:["[Console] Sending a request to the servers..."],replaceto:[ "[Consola] Envío de una solicitud a los servidores ..."]};
this.lang[160] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[161] = { original:["[Console] Allowed player "," To chat"],replaceto:[ "[Consola] reproductor de mascotas", "para conversar"]};
this.lang[162] = { original:["[Console] Banned player "," From chat"],replaceto:[ "[Consola] reproductor prohibido", "De la charla"]};
this.lang[163] = { original:["[Console] Cleared "," IP's"],replaceto:[ "[Consola] Borrado", "IP"]};
this.lang[164] = { original:["[Console] Cleared "," IP's"],replaceto:[ "[Consola] Borrado", "IP"]};
this.lang[165] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[166] = { original:["Set the color of "," to ",", ",", "," "],replaceto:[ "Establecer el color de", "a"]};
this.lang[167] = { original:["\x1b[31mText is now Red"],replaceto:[ "\ X1B [31mText es ahora Red"]};
this.lang[168] = { original:["\x1b[32mText is now Green"],replaceto:[ "\ X1B [32mText es ahora verde"]};
this.lang[169] = { original:["\x1b[34mText is now Blue"],replaceto:[ "\ X1B [34mText ahora es azul"]};
this.lang[170] = { original:["\x1b[33mText is now Yellow"],replaceto:[ "\ X1B [33mText es ahora Amarillo"]};
this.lang[171] = { original:["\x1b[0mText is now Reset"],replaceto:[ "\X1B[0mText es ahora de reinicio"]};
this.lang[172] = { original:["\x1b[1mText is now Bold"],replaceto:[ "\ X1B [1mText es ahora Bold"]};
this.lang[173] = { original:["\x1b[37mText is now White"],replaceto:[ "\ X1B [37mText es ahora blanco"]};
this.lang[174] = { original:["\x1b[2mText is now Dim"],replaceto:[ "\ X1B [2mText es ahora Dim"]};
this.lang[175] = { original:["----- Colortext Help -----"],replaceto:[ "----- ----- ColorText Ayuda"]};
this.lang[176] = { original:["Red"],replaceto:["Rojo"]};
this.lang[177] = { original:["Green"],replaceto:["Verde"]};
this.lang[178] = { original:["Blue"],replaceto:["Azul"]};
this.lang[179] = { original:["White"],replaceto:["Blanco"]};
this.lang[180] = { original:["Yellow"],replaceto:["Amarillo"]};
this.lang[181] = { original:["Dim"],replaceto:["Oscuro"]};
this.lang[182] = { original:["Bold"],replaceto:["Negrita"]};
this.lang[183] = { original:["Reset"],replaceto:["Reiniciar"]};
this.lang[184] = { original:["Please specify a valid style or do Colortext help for a list"],replaceto:[ "Por favor especificar un estilo válido o hacer colorText ayuda de una lista"]};
this.lang[185] = { original:["[Console] Do delete yes to confirm"],replaceto:[ "[Consola] Foro de borrar Sí para confirmar"]};
this.lang[186] = { original:["[Delete] Deleting files"],replaceto:[ "[Eliminar] Eliminación de archivos"]};
this.lang[187] = { original:["[Update] Done! Now restarting/closing..."],replaceto:[ "[Actualización] Hecho! Ahora reiniciar / cerrar ..."]};
this.lang[188] = { original:["\x1b[0m[Console] Closing server..."],replaceto:[ "\X1B[0m [consola] servidor de cierre ..."]};
this.lang[189] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[190] = { original:["[ForceMSG] The message has been broadcast"],replaceto:[ "[ForceMSG] El mensaje ha sido transmitido"]};
this.lang[191] = { original:["[ForceMSG] The game has been reset"],replaceto:[ "[ForceMSG] El juego se ha restablecido"]};
this.lang[192] = { original:["[Console] Invalid coordinates"],replaceto:[ "[Consola] coordenadas no válidas"]};
this.lang[193] = { original:["[Console] Spawned 1 food cell at ("," , ",")"],replaceto:[ "[Consola] Spawned 1 célula comida en (" ,",", ")"]};
this.lang[194] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[195] = { original:["Garbage collecting in "," minutes!"],replaceto:[ "Recolección de basura en", "minutos!"]};
this.lang[196] = { original:["Garbage Collecting in 1 Minute"],replaceto:[ "Recogida de la basura en 1 minuto"]};
this.lang[197] = { original:["\x1b[0m[Console] Garbage Collecting..."],replaceto:[ "\X1B[0m [consola] recolección de basura ..."]};
this.lang[198] = { original:["[Console] Next garbage collection scheduled"],replaceto:[ "[Consola] Siguiente recolección de basura programada"]};
this.lang[199] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[200] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[201] = { original:["[Console] Kicked all bots (",")"],replaceto:[ "[Consola] golpeado con el pie todos los bots (", ")"]};
this.lang[202] = { original:["[Console] Kicked "," bots"],replaceto:[ "[Consola] golpeado con el pie", "bots"]};
this.lang[203] = { original:["[Console] Please specify a valid range!"],replaceto:[ "[Consola] Por favor, especifique un rango válido!"]};
this.lang[204] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[205] = { original:["[Console] Killed player "," and removed "," cells"],replaceto:[ "[Consola] jugador Muerto", "y se retira", "células"]};
this.lang[206] = { original:["[Console] Removed "," cells"],replaceto:[ "[Consola] Se ha eliminado", "células"]};
this.lang[207] = { original:["[Console] Killed all bots (",")"],replaceto:[ "[Consola] mató a todos los robots (", ")"]};
this.lang[208] = { original:["[Console] Killed "," bots"],replaceto:[ "[Consola] Muerto", "bots"]};
this.lang[209] = { original:["[Console] Only "," bots could be killed"],replaceto:[ "[Consola] Solo", "los robots podrían morir"]};
this.lang[210] = { original:["[Console] Please specify a valid range!"],replaceto:[ "[Consola] Por favor, especifique un rango válido!"]};
this.lang[211] = { original:["[Console] Removed "," cells"],replaceto:[ "[Consola] Se ha eliminado", "células"]};
this.lang[212] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[213] = { original:["[Console] Please specify a valid number"],replaceto:[ "[Consola] Por favor, especifique un número válido"]};
this.lang[214] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[215] = { original:["[Console] Forced "," to merge cells"],replaceto:[ "[Consola] forzado", "para combinar celdas"]};
this.lang[216] = { original:["[Console] Succesfully destroyed all minions"],replaceto:[ "[Consola] Succesfully destruyó todas secuaces"]};
this.lang[217] = { original:["[Console] Please specify a valid id!"],replaceto:[ "[Consola] Por favor especificar un ID válido!"]};
this.lang[218] = { original:["[MSG] The message has been broadcast"],replaceto:[ "[MSG] El mensaje ha sido transmitido"]};
this.lang[219] = { original:["[MSG] The board has been reset"],replaceto:[ "[MSG] La placa se ha restablecido"]};
this.lang[220] = { original:["[Console] Please specify a port"],replaceto:[ "[Consola] Por favor, especifique un puerto"]};
this.lang[221] = { original:["[Console] That name/port is already taken!"],replaceto:[ "[Consola] Ese nombre / puerto ya está en uso!"]};
this.lang[222] = { original:["[Console] Failed to remove server. Check it is not master or selected"],replaceto:[ "[Consola] No se ha podido eliminar el servidor. Hay que ver no es dueño o se selecciona"]};
this.lang[223] = { original:["[Console] Please specify a command! (list, select,remove,create)"],replaceto:[ "[Consola] Por favor, especifique un comando! (Lista, seleccionar, eliminar, crear)"]};
this.lang[224] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[225] = { original:["[Console] Please type a valid name"],replaceto:[ "[Consola] Por favor introduce un nombre válido"]};
this.lang[226] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[227] = { original:["Player "," cannot recombine now"],replaceto:[ "Jugador", "no se puede recombinar ahora"]};
this.lang[228] = { original:["[Console] ======================= OP HELP ====================="],replaceto:[ "[Consola] ======================= OP AYUDA ==================== = "]};
this.lang[229] = { original:["You use OP by first setting who has op by doing op [id] in console. Then, that player can use the op features in game by pressing q. Then a c will appear next to your name. If you press w in this state, it gives you 100 more mass. If you press space in this state, you will be able to rejoin instantly. You will find out that if you press q again, two c's will appear next to your name. if you press w in this state, you shoot viruses. If you press space in this state, you shoot tiny things (almost invisible) that if someone eats, their mass is reduced by 100. Then, if you press q again,3 c's will appear.press w with 3c's, you shoot a virus, but whoever who eats it will be trolled :). If you press space with 3 c's the person who eats the virus will explode.If you press q again, 4 cs will appear and if you press w, you will shoot a virus tha kills people and space, it shoots a kick virus. You can then exit op by pressing q again after doing an action or by pressing Q until the three c's will dissappear (so that you can normally split and shoot mass)."],replaceto:[ "Se utiliza OP por primera configuración que tiene op haciendo op [id] en la consola. Luego, ese jugador puede utilizar las funciones operacionales en juego pulsando q. Entonces ac aparecerá junto a su nombre. Si pulsa w en este estado, se le da el 100 más masa. Si pulsa el espacio en este estado, usted será capaz de unirse al instante. va a descubrir que si presiona q otra vez, dos c del aparecerán junto a su nombre. Si presiona w en este estado, disparar virus. Si pulsa el espacio en este estado, se dispara cosas pequeñas (casi invisible) que si alguien come, su masa se reduce en 100. Entonces, si se pulsa de nuevo q, 3 c de Will appear.press w con 3C, se dispara un virus, pero el que quien lo come será controlada :). Si pulsa el espacio con 3 c de la persona que come el virus se explode.If presiona q de nuevo, aparecerá 4 cs y si presiona w , que va a capturar un tha virus mata gente y el espacio, que dispara un virus patada. a continuación, puede salir op pulsando q de nuevo después de hacer una acción o pulsando q hasta que las tres C se dissappear (de modo que normalmente se pueden dividir y disparar masa)."]};
this.lang[230] = { original:["[Console] ===================== OP Usage Map ==================="],replaceto:[ "[Consola] ===================== OP Uso Mapa ==================="]};
this.lang[231] = { original:["One C:"],replaceto:[ "Un C:"]};
this.lang[232] = { original:["W = Addmass 100+"],replaceto:[ "W = 100 + Addmass"]};
this.lang[233] = { original:["Space = Merge Instantly"],replaceto:[ "Espacio = Combinar de forma instantánea"]};
this.lang[234] = { original:["Two C's:"],replaceto:[ "Dos de C:"]};
this.lang[235] = { original:["W = Shoot virus"],replaceto:[ "W = disparar virus"]};
this.lang[236] = { original:["Space = Shoot Mass that decreases 100 mass from consumer"],replaceto:[ "Espacio = Disparar misa que disminuye la masa de 100 consumidores"]};
this.lang[237] = { original:["Three C's:"],replaceto:[ "Tres C:"]};
this.lang[238] = { original:["W = Troll virus"],replaceto:[ "Virus W = Troll"]};
this.lang[239] = { original:["Space = Explode virus"],replaceto:[ "Espacio = estalla el virus"]};
this.lang[240] = { original:["Four C's:"],replaceto:[ "Cuatro C:"]};
this.lang[241] = { original:["W = Kill virus"],replaceto:[ "Virus W = Kill"]};
this.lang[242] = { original:["Space = Kick Virus"],replaceto:[ "Espacio = Virus del retroceso"]};
this.lang[243] = { original:["[Console] ===================================================="],replaceto:[ "[Consola] ============================================= ======= "]};
this.lang[244] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[245] = { original:["[Console] Made "," OP"],replaceto:[ "[Consola] Hecho", "OP"]};
this.lang[246] = { original:["[Console] Added "," to the opbyip list"],replaceto:[ "[Consola] Añadido", "a la lista opbyip"]};
this.lang[247] = { original:["[Console] That ip is already listed"],replaceto:[ "[Consola] Eso IP ya está en la lista"]};
this.lang[248] = { original:["[Console] Removed "," from the opbyip list"],replaceto:[ "[Consola] Se ha eliminado", "de la lista opbyip"]};
this.lang[249] = { original:["[Console] That ip is already not in the list"],replaceto:[ "[Consola] que la propiedad intelectual ya no está en la lista"]};
this.lang[250] = { original:["[Console] Cleared opbyip list"],replaceto:[ "[Consola] Borrado opbyip lista"]};
this.lang[251] = { original:["[Console] Succesfully cleared recorded opbyip"],replaceto:[ "[Consola] Succesfully aclaró opbyip grabada"]};
this.lang[252] = { original:["[Console] Succesfully recorded opbyip"],replaceto:[ "[Consola] Succesfully registró opbyip"]};
this.lang[253] = { original:["[Console] Please type in a valid command, add, remove, list, clear, record"],replaceto:[ "[Consola] Por favor, escriba un comando válido, añadir, eliminar, lista, claro, ficha"]};
this.lang[254] = { original:["[Console] "," the game."],replaceto:[ "[Consola]", "juego"]};
this.lang[255] = { original:["[PCMD] Disabled all running pcmd instances"],replaceto:[ "[PCMD] Desactivado todas las instancias que ejecutan PCMD"]};
this.lang[256] = { original:["[Console] Please specify a valid Repeat amount!"],replaceto:[ "[Consola] Por favor, especifique una cantidad de repetición válida!"]};
this.lang[257] = { original:["[Console] Please specify a valid delay!"],replaceto:[ "[Consola] Por favor, especifique un retraso válida!"]};
this.lang[258] = { original:["[PCMD] Request Sent!"],replaceto:[ "[PCMD] Solicitud enviado!"]};
this.lang[259] = { original:["[PCMD] Running command."],replaceto:[ "Ejecución de comandos [PCMD]."]};
this.lang[260] = { original:["[PCMD] Done"],replaceto:[ "[PCMD] Hecho"]};
this.lang[261] = { original:["[Console] Please specify a valid delay!"],replaceto:[ "[Consola] Por favor, especifique un retraso válida!"]};
this.lang[262] = { original:["[Console] Please specify a valid duration!"],replaceto:[ "[Consola] Por favor, especifique una duración válida!"]};
this.lang[263] = { original:["[Console] Please specify a valid times to repeat!"],replaceto:[ "[Consola] Por favor, especifica un momento válidos para repetir!"]};
this.lang[264] = { original:["[PFMSG] Your request has been sent"],replaceto:[ "[PFMSG] Su solicitud ha sido enviado"]};
this.lang[265] = { original:["[PFMSG] Done"],replaceto:[ "[PFMSG] Hecho"]};
this.lang[266] = { original:["[Console] Showing "," players: "],replaceto:[ "[Consola] Mostrando", "los jugadores:"]};
this.lang[267] = { original:[" ID         | IP              | "," | CELLS | SCORE  | POSITION    "],replaceto:[ "Identificación | IP |", "| CÉLULAS | SCORE posición |"]};
this.lang[268] = { original:["[Console] --------------- Installed Plugins ---------------"],replaceto:[ "[Consola] --------------- --------------- plugins instalados"]};
this.lang[269] = { original:["[Console] "," By "," version ","\n      Description: ","[Console] "," By "," version ","\n      Description: No description given"],replaceto:[ "[Consola]", "Por", "versión", "\ n Descripción:", "versión", "\ n Descripción: No hay descripción dada", "[consola]", "Por"]};
this.lang[270] = { original:["[Console] ------------------------------------------------"],replaceto:["[Consola] --------------------------------------------- --- "]};
this.lang[271] = { original:["[Console] Please enter a search term!"],replaceto:[ "[Consola] Por favor, introduzca un término de búsqueda!"]};
this.lang[272] = { original:["[Console] Connecting to servers..."],replaceto:[ "[Consola] La conexión a servidores ..."]};
this.lang[273] = { original:["[Console] Search results for "," :"],replaceto:[ "[Consola] Resultados de la búsqueda para"," :"]};
this.lang[274] = { original:["[Console] Reloaded plugins"],replaceto:[ "[Consola] plugins Reloaded"]};
this.lang[275] = { original:["[Console] Done, Reloading..."],replaceto:[ "[Consola] Hecho, volver a cargar ..."]};
this.lang[276] = { original:["[Console] You cannot install a plugin unless directly at the console!"],replaceto:[ "[Consola] No es posible instalar un plugin menos directamente en la consola!"]};
this.lang[277] = { original:["[Console] Since you did not specify a valid save-as file name, we will generate a random one"],replaceto:[ "[Consola] Dado que no se ha especificado un válidos salvo, como nombre de archivo, vamos a generar al azar"]};
this.lang[278] = { original:["[Console] Downloading..."],replaceto:[ "[Consola] Descargando ..."]};
this.lang[279] = { original:["[Update] Please put a valid url of the raw files.txt file"],replaceto:[ "[Actualización] Por favor, ponga una URL válida del archivo lista.txt prima"]};
this.lang[280] = { original:["[Console] Please specify a valid delay!"],replaceto:[ "[Consola] Por favor, especifique un retraso válida!"]};
this.lang[281] = { original:["[Console] Please specify a valid duration!"],replaceto:[ "[Consola] Por favor, especifique una duración válida!"]};
this.lang[282] = { original:["[Console] Please specify a valid times to repeat!"],replaceto:[ "[Consola] Por favor, especifica un momento válidos para repetir!"]};
this.lang[283] = { original:["[PMSG] Your request has been sent"],replaceto:[ "[PMSG] Su solicitud ha sido enviado"]};
this.lang[284] = { original:["[PMSG] Done"],replaceto:[ "[PMSG] Hecho"]};
this.lang[285] = { original:["[Console] Quickrestarting servers..."],replaceto:[ "[Consola] servidores Quickrestarting ..."]};
this.lang[286] = { original:["[Console] Restarted servers successfully"],replaceto:[ "[Consola] reinicia servidores éxito"]};
this.lang[287] = { original:["[Console] Please specify a player!"],replaceto:[ "[Consola] Por favor, especifique un jugador!"]};
this.lang[288] = { original:["[Console] Please specify a valid range!"],replaceto:[ "[Consola] Por favor, especifique un rango válido!"]};
this.lang[289] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[290] = { original:["[Console] Logged in "," as admin"],replaceto:[ "[Consola] Conectado", "como administrador"]};
this.lang[291] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[292] = { original:["[Console] Logged out "," as admin"],replaceto:[ "[Consola] Acceso a cabo", "como administrador"]};
this.lang[293] = { original:["[Console] Reloaded the config files successfully"],replaceto:[ "[Consola] Reloaded los archivos de configuración con éxito"]};
this.lang[294] = { original:["[Console] Reset the game"],replaceto:[ "[Consola] Reiniciar el juego"]};
this.lang[295] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[296] = { original:["[Console] Client is nonexistent!"],replaceto:[ "[Consola] cliente es inexistente!"]};
this.lang[297] = { original:["[Console] Successfully reset client's anti-team effect"],replaceto:[ "[Consola] restablecer con éxito el efecto anti-equipo del cliente"]};
this.lang[298] = { original:["[Console] Turned any Special Viruses (from op's) Into normal ones"],replaceto:[ "[Consola] Resultó cualquier tipo de virus especiales (de op) en otras más normales"]};
this.lang[299] = { original:["\x1b[0m[Console] Restarting server..."],replaceto:[ "\X1B[0m [consola] servidor reiniciando ..."]};
this.lang[300] = { original:["Server Restarting in "," minutes!"],replaceto:[ "Servidor de Reinicio en", "minutos!"]};
this.lang[301] = { original:["The Server is Restarting in 1 Minute"],replaceto:[ "Se reinicia el servidor en 1 minuto"]};
this.lang[302] = { original:["\x1b[0m[Console] Restarting server..."],replaceto:[ "\X1B[0m [consola] servidor reiniciando ..."]};
this.lang[303] = { original:["Reset OP"],replaceto:[ "Reset OP"]};
this.lang[304] = { original:["[Console] Spawn Command Help - To use do spawn [cellname] [x] [y] [mass] [stage(for beacons)]"],replaceto:[ "[Consola] Ayuda freza Comando - Para utilizar hacer desove [nombrecélula] [x] [y] [masa] [etapa (por balizas)]"]};
this.lang[305] = { original:["[Console] food       : Spawns food"],replaceto:[ "[Consola] alimentos: Genera alimentos"]};
this.lang[306] = { original:["[Console] virus      : Spawns virus "],replaceto:[ "[Consola] virus: Genera virus"]};
this.lang[307] = { original:["[Console] mvirus     : Spawns Moving virus"],replaceto:[ "[Consola] mvirus: Desova Moving virus"]};
this.lang[308] = { original:["[Console] mfood      : Spawns Moving Food"],replaceto:[ "[Consola] mfood: Desova transporte de los alimentos"]};
this.lang[309] = { original:["[Console] Mothercell : Spawns mothercell"],replaceto:[ "[Consola] Mothercell: Genera mothercell"]};
this.lang[310] = { original:["[Console] Stickycell : spawns Stickycell"],replaceto:[ "[Consola] Stickycell: genera Stickycell"]};
this.lang[311] = { original:["[Console] Beacon     : Spawns beacon"],replaceto:[ "[Consola] Beacon: Genera faro"]};
this.lang[312] = { original:["[Console] help       : shows help"],replaceto:[ "[Consola] ayuda: muestra ayuda"]};
this.lang[313] = { original:["[Console] Please type in a valid coordinate"],replaceto:[ "[Consola] Por favor escriba en un válido de coordenadas"]};
this.lang[314] = { original:["[Console] Please type in a valid coordinate"],replaceto:[ "[Consola] Por favor escriba en un válido de coordenadas"]};
this.lang[315] = { original:["[Console] Please type in valid mass"],replaceto:[ "[Consola] Por favor escriba en la masa válida"]};
this.lang[316] = { original:["[Console] Spawned 1 food cell at ("," , ",")"],replaceto:[ "[Consola] Spawned 1 célula comida en (" ,",", ")"]};
this.lang[317] = { original:["[Console] Spawned 1 virus at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 virus en las coordenadas (", ",", ") con una masa de"]};
this.lang[318] = { original:["[Console] Spawned 1  Moving virus at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 Moving virus en las coordenadas (", ",", ") con una masa de"]};
this.lang[319] = { original:["[Console] Spawned 1  Moving Food at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 paso de los alimentos en las coordenadas (" ,",", ") con una masa de"]};
this.lang[320] = { original:["[Console] Spawned 1  Mothercell at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 Mothercell en las coordenadas (", ",", ") con una masa de"]};
this.lang[321] = { original:["[Console] Spawned 1  StickyCell at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 StickyCell en las coordenadas (", ",", ") con una masa de"]};
this.lang[322] = { original:["[Console] Spawned 1  Beacon at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 Beacon en las coordenadas (", ",", ") con una masa de"]};
this.lang[323] = { original:["[Console] Please type in a valid cell name or do spawn help to get help"],replaceto:[ "[Consola] Por favor, escriba un nombre de celda válida o hacer ayuda desove para obtener ayuda"]};
this.lang[324] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[325] = { original:["[Console] Please specify a valid mass!"],replaceto:[ "[Consola] Por favor, especifique una masa válida!"]};
this.lang[326] = { original:["[Console] Player "," now spawns with "," Mass"],replaceto:[ "[Consola] Jugador", "ahora genera con", "Masa"]};
this.lang[327] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[328] = { original:["[Console] Please specify a valid speed!"],replaceto:[ "[Consola] Por favor, especifique una velocidad válida!"]};
this.lang[329] = { original:["[Console] You have no SPFMSG Process"],replaceto:[ "[Consola] No tienes Proceso SPFMSG"]};
this.lang[330] = { original:["[Console] Stopped any periodicForceMSG process"],replaceto:[ "[Consola] Detenido cualquier proceso periodicForceMSG"]};
this.lang[331] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[332] = { original:["[Console] Since you did not specify split count, We will split the person into 16 cells"],replaceto:[ "[Consola] Dado que no se ha especificado el recuento de división, nos va a dividir a la persona en 16 celdas"]};
this.lang[333] = { original:["[Console]","Is greater than the max cells, split into the max cell amount"],replaceto:[ "[Consola]", "¿Es mayor que las células max, dividido en la cantidad de células max"]};
this.lang[334] = { original:["[Console] Forced "," to split cells"],replaceto:[ "[Consola] forzado", "para dividir celdas"]};
this.lang[335] = { original:["[Console] You have no PMSG Process"],replaceto:[ "[Consola] No tiene ningún proceso de PMSG"]};
this.lang[336] = { original:["[Console] Stopped any periodicMSG process"],replaceto:[ "[Consola] Detenido cualquier proceso periodicMSG"]};
this.lang[337] = { original:["[Console] Current memory usage: ","/"," kb"],replaceto:[ "[Consola] el uso de memoria actual:", "/", "kb"]};
this.lang[338] = { original:["[Console] Please specify a team (r,g,b)"],replaceto:[ "[Consola] Por favor, especifique un equipo (r, g, b)"]};
this.lang[339] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[340] = { original:["[Console] Successively changed the players team"],replaceto:[ "[Consola] Sucesivamente cambió el equipo de jugadores"]};
this.lang[341] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[342] = { original:["[Console] Invalid coordinates"],replaceto:[ "[Consola] coordenadas no válidas"]};
this.lang[343] = { original:["[Console] Teleported "," to ("," , ",")"],replaceto:[ "[Consola] Teleported", "para (" ,",", ")"]};
this.lang[344] = { original:["[Console] Please specify a valid player ID!"],replaceto:[ "[Consola] Por favor, especifique un ID de jugador válida!"]};
this.lang[345] = { original:["[Console] Player "," Was Trolled"],replaceto:[ "[Consola] Jugador", "fue controlada"]};
this.lang[346] = { original:["[Console] Current UniBanned IPs (",")"],replaceto:[ "[Consola] actual UniBanned IPs (", ")"]};
this.lang[347] = { original:["[Update] Updating Botnames"],replaceto:[ "[Actualización] Actualización Botnames"]};
this.lang[348] = { original:["[Console] Updating customskin.txt..."],replaceto:[ "[Consola] Actualización customskin.txt ..."]};
this.lang[349] = { original:["[Console] Fetching data from the servers..."],replaceto:[ "[Consola] Obtención de datos de los servidores ..."]};
this.lang[350] = { original:["[Console] Fetching data from the servers..."],replaceto:[ "[Consola] Obtención de datos de los servidores ..."]};
this.lang[351] = { original:["[Console] Please do update updates, all, botnames, or skins instead of update to confirm."],replaceto:[ "[Consola] Por favor, actualizaciones de actualización, todos, botnames, o pieles en lugar de actualización para confirmar."]};
this.lang[352] = { original:["[Console] Please specify a valid id!"],replaceto:[ "[Consola] Por favor especificar un ID válido!"]};
this.lang[353] = { original:["[Console] Made Player "," Reverify"],replaceto:[ "[Consola] Hecho del jugador", "Volver a verificar"]};
this.lang[354] = { original:["[Console] Plese specify a command, Verify or reverify!"],replaceto:[ "[Consola] Plese especificar un comando, verificar una o dos!"]};
this.lang[355] = { original:["[Console] Invalid coordinates"],replaceto:[ "[Consola] coordenadas no válidas"]};
this.lang[356] = { original:["[Console] Spawned 1 virus at coordinates ("," , ",") with a mass of "," "],replaceto:[ "[Consola] Spawned 1 virus en las coordenadas (", ",", ") con una masa de"]};
this.lang[357] = { original:["[Console] Added "," to the whitelist"],replaceto:[ "[Consola] Añadido", "a la lista blanca"]};
this.lang[358] = { original:["[Console] That IP is already whitelisted"],replaceto:[ "[Consola] Eso IP ya está en la lista blanca"]};
this.lang[359] = { original:["[Console] Current whitelisted IPs (",")"],replaceto:[ "[Consola] IPs lista blanca actual (", ")"]};
this.lang[360] = { original:["[Console] Added "," to the whitelist"],replaceto:[ "[Consola] Añadido", "a la lista blanca"]};
this.lang[361] = { original:["[Console] That IP is already whitelisted"],replaceto:[ "[Consola] Eso IP ya está en la lista blanca"]};
module.exports = this;
